export const ADD_EVENT = 'ADD_EVENT';
export const CHANGE_ADD_INTERSECTED_EVENT = "CHANGE_ADD_INTERSECTED_EVENT";



// dateReducer
export const CHANGE_DATE = 'CHANGE_DATE';
export const MONTH_FORWARD = 'MONTH_FORWARD';
export const MONTH_BACKWARD = 'MONTH_BACKWARD';

// addEventReducer
export const ENTER_EVENT_MESSAGE = 'ENTER_EVENT_MESSAGE';
export const CHANGE_DATE_EVENT_ADDITION = 'CHANGE_DATE_EVENT_ADDITION';
export const ENTER_EVENT_START_TIME = 'ENTER_EVENT_START_TIME';
export const ENTER_EVENT_END_TIME = 'ENTER_EVENT_END_TIME';
export const SELECT_USE_TIME = 'SELECT_USE_TIME';
export const SELECT_ANNUAL_EVENT = 'SELECT_ANNUAL_EVENT';
export const INVERT_TIME_IS_VALID = 'INVERT_TIME_IS_VALID';
export const INVERT_MESSAGE_IS_VALID = 'INVERT_MESSAGE_IS_VALID';
export const SET_MESSAGE_ADDITION_SUCCESS = 'INVERT_MESSAGE_ADDITION_SUCCESS';
export const RESET_MESSAGE_ADDITION_SUCCESS = 'RESET_MESSAGE_ADDITION_SUCCESS';
export const INVERT_ADD_INTERSECTED_EVENT = 'INVERT_ADD_INTERSECTED_EVENT';
export const SET_ADD_INTERSECTED_EVENT = 'SET_ADD_INTERSECTED_EVENT';
export const RESET_ADD_INTERSECTED_EVENT = 'RESET_ADD_INTERSECTED_EVENT';

// dayCellReducer
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_MODAL_BY_DAY = 'TOGGLE_MODAL_BY_DAY';
export const ADD_INITIAL_CELL_STATE = 'ADD_INITIAL_CELL_STATE';

// typeViewReducer
export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';